// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package rooms

import (
	"context"
)

type Querier interface {
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	DeleteRoom(ctx context.Context, id int64) error
	GetRoomsByMeeting(ctx context.Context, meetingID int64) ([]Room, error)
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) error
}

var _ Querier = (*Queries)(nil)
