// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sessions

import (
	"context"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteSession(ctx context.Context, id int64) error
	GetSessionsByRoom(ctx context.Context, roomID int64) ([]Session, error)
	UpdateSession(ctx context.Context, arg UpdateSessionParams) error
}

var _ Querier = (*Queries)(nil)
