// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package house_visits

import (
	"context"
	"time"
)

type Querier interface {
	CreateHouseVisit(ctx context.Context, arg CreateHouseVisitParams) (HouseVisit, error)
	DeleteHouseVisit(ctx context.Context, id int64) error
	GetHouseVisitsPaginated(ctx context.Context, arg GetHouseVisitsPaginatedParams) ([]HouseVisit, error)
	GetVisitsByDate(ctx context.Context, visitDate time.Time) ([]HouseVisit, error)
	GetVisitsByHouseNumber(ctx context.Context, arg GetVisitsByHouseNumberParams) ([]HouseVisit, error)
	GetVisitsByTerritory(ctx context.Context, territoryID int64) ([]HouseVisit, error)
	UpdateHouseVisit(ctx context.Context, arg UpdateHouseVisitParams) error
}

var _ Querier = (*Queries)(nil)
