// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package cart_shifts

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateCartShift(ctx context.Context, arg CreateCartShiftParams) (CartShift, error)
	DeleteCartShift(ctx context.Context, id int64) error
	GetAvailableCartShifts(ctx context.Context, arg GetAvailableCartShiftsParams) ([]sql.NullString, error)
	GetCartShiftsByDay(ctx context.Context, shiftDay int32) ([]CartShift, error)
	UpdateCartShift(ctx context.Context, arg UpdateCartShiftParams) error
}

var _ Querier = (*Queries)(nil)
