// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package carts

import (
	"context"
)

type Querier interface {
	CreateCart(ctx context.Context, arg CreateCartParams) (Cart, error)
	DeleteCart(ctx context.Context, id int64) error
	GetAllCarts(ctx context.Context) ([]Cart, error)
	UpdateCart(ctx context.Context, arg UpdateCartParams) error
}

var _ Querier = (*Queries)(nil)
