// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package territories

import (
	"context"
)

type Querier interface {
	CreateTerritory(ctx context.Context, arg CreateTerritoryParams) (Territory, error)
	DeleteTerritory(ctx context.Context, id int64) error
	GetAllTerritories(ctx context.Context) ([]Territory, error)
	GetCompletedTerritories(ctx context.Context) ([]Territory, error)
	GetTerritoriesPaginated(ctx context.Context, arg GetTerritoriesPaginatedParams) ([]Territory, error)
	GetTerritoryByID(ctx context.Context, id int64) (Territory, error)
	MarkTerritoryAsCompleted(ctx context.Context, arg MarkTerritoryAsCompletedParams) error
	ReopenTerritory(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
