// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package subsessions

import (
	"context"
)

type Querier interface {
	CreateSubsession(ctx context.Context, arg CreateSubsessionParams) (Subsession, error)
	DeleteSubsession(ctx context.Context, id int64) error
	GetSubsessionsBySession(ctx context.Context, sessionID int64) ([]Subsession, error)
	UpdateSubsession(ctx context.Context, arg UpdateSubsessionParams) error
}

var _ Querier = (*Queries)(nil)
