// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package cart_assignments

import (
	"context"
)

type Querier interface {
	AssignUserToCartShift(ctx context.Context, arg AssignUserToCartShiftParams) (CartAssignment, error)
	DeleteCartAssignment(ctx context.Context, id int64) error
	GetCartAssignmentsByShift(ctx context.Context, shiftID int64) ([]CartAssignment, error)
}

var _ Querier = (*Queries)(nil)
