// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package cleaning

import (
	"context"
)

type Querier interface {
	AssignCleaning(ctx context.Context, arg AssignCleaningParams) (CleaningAssignment, error)
	DeleteCleaningAssignment(ctx context.Context, id int64) error
	GetCleaningAssignmentsByMeeting(ctx context.Context, meetingID int64) ([]CleaningAssignment, error)
}

var _ Querier = (*Queries)(nil)
